services:
  bot:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/pwuser/redashbot
    environment:
      - DEBUG
      - REDASH_HOST
      - REDASH_HOST_ALIAS
      - REDASH_API_KEY
      - REDASH_HOSTS_AND_API_KEYS
      - REDASH_CUSTOM_HEADERS
      - SLACK_BOT_TOKEN
      - SLACK_SIGNING_SECRET
      - PORT
      - BROWSER
      - SLEEP_TIME
